version: "3.9"

services:
  db:
    image: postgres:16
    container_name: pet-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pet_adoption
    ports:
      - "5434:5432"
    volumes:
      - pet_pg_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: pet-adoption-api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: pet_adoption

      # if your config.LoadEnv uses these:
      JWT_SECRET: supersecretkey
      SERVER_PORT: "8080"
    ports:
      - "8080:8080"
    # if you need live reload in dev, you could mount:
    # volumes:
    #   - .:/app

volumes:
  pet_pg_data:
